[package]
name = "novelang"
version = "0.1.0"
authors = ["equal-l2 <eng.equall2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.17.1"
ctrlc = { version = "3.1.4", features = ["termination"] }
structopt = "0.3.12"
rand = "0.7.3"
