[package]
name = "novelang"
version = "0.1.0"
authors = ["equal-l2 <eng.equall2@gmail.com>"]
edition = "2018"

[dependencies]
structopt = { version = "0.3.21", default-features = false }
rand = { version = "0.8.4", default-features = false, features = ["getrandom", "small_rng"] }
